name: Test

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: Build
        run: cargo build --release

      - name: Test Correct
        run: ./target/release/modlinks-sha-verifier mod ./test/modlinks/correct.xml

      - name: Test Incorrect
        run: ./target/release/modlinks-sha-verifier mod ./test/modlinks/incorrect.xml
        continue-on-error: true

      - name: Test Invalid
        run: ./target/release/modlinks-sha-verifier mod ./test/modlinks/invalid.xml
        continue-on-error: true
